homeassistant:
  # Name of the location where Home Assistant is running
  name: Fox Home
  # Location required to calculate the time the sun rises and sets
  latitude: 25.0389
  longitude: 102.7183
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Shanghai



###delete this part after finish#####
switch:
  - platform: broadlink
    host: 192.168.100.19
    mac: "B4:43:0D:10:04:5A"
    friendly_name: "example"
    timeout: 30
    type: rm2
    switches:
      tv_box:
        command_on: "abc"
        command_off: "abc"
        friendly_name: 'example'
###delete this part after finish#####


#group: !include foxgroup.yaml
#script: !include foxscript.yaml


# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

#######receive from broadlink
logger:
  default: critical
  logs:
    homeassistant.components.switch.broadlink: info

# Text to speech
tts:
  platform: google

automation: !include automations.yaml
